### PR TITLE
Sharpen refactored as command-line maven package

### LINKED ISSUE #54: Operating independently of Eclipse
Does anyone have any suggestions for creating a command-line version of sharpen that does not have an Eclipse dependency? (Such as for use on a build server). Any suggestions for a replacement source code parser system?

https://github.com/INRIA/spoon
http://www.monperrus.net/martin/jexast
https://github.com/matozoid/javaparser
http://docs.oracle.com/javase/7/docs/jdk/api/javac/tree/com/sun/source/tree/package-summary.html

### PR DESCRIPTION
**Pull request by nathanaeljones**
Fixes #54 

All 278 tests pass on OS X, although 7 fail on linux for what I think are file path issues.

To generate github release keys for `slluis/sharpen`, [run `travis setup releases`](http://docs.travis-ci.com/user/deployment/releases/) and commit .travis.yml (removing duplicate entries, of course).

Feedback welcomed

### CODE REVIEW

**Comment by hazzik** [comment]
:+1:

**Comment by hazzik** [comment]
@nathanaeljones can you provide a jar file?

**Comment by nathanaeljones** [comment]
Yes, we have travis set up to publish a self-contained jar file anytime we tag a commit with a semver.

**Comment by nathanaeljones** [comment]
Hi, I'd like to move forward with some larger, dependent tasks, like cleaning up the folder structure and removing plugin-related files. Could we decide about the future of this pull request? If it should remain a separate fork, then we won't need to keep maintaining 2 branches of our changes.

**Comment by nathanaeljones** [comment]
@hazzik See https://github.com/imazen/sharpen/releases/tag/v0.1.4

**Comment by nathanaeljones** [comment]
@slluis, could you provide feedback on whether this change is aligned with your goals for the project?

**Comment by slluis** [comment]
I think Sharpen is more useful as command line tool, so the change looks good to me.

**Pull request merged**
