### PR TITLE
Reorganize to standard maven folder structure, add code quality reporting

### PR DESCRIPTION
**Pull request by nathanaeljones**
This PR also includes a set of badges for slluis/sharpen. You will need to log into Travis and AppVeyor both, and activate slluis/sharpen with both, then edit readme.md and insert your AppVeyor project id in both links.

You'll also want to generate your github release token (if you want automatic release preparation). 'travis setup releases' -> http://docs.travis-ci.com/user/deployment/releases/

### CODE REVIEW

**Comment by nathanaeljones** [comment]
*bump*

This repo is google result #1 for sharpen. Do you have any collaborators authorized to assist with maintenance?

**Comment by slluis** [comment]
@nathanaeljones do you want to take over the project? I think it would be the best option.

**Comment by nathanaeljones** [comment]
I would be happy to. We have a lot of improvements planned, since we want a long-term automated port of MetadataExtractor. I'd like to get the issue list somehow - but I think to do that, you would have to transfer the repository to me, then re-fork it?

**Comment by nathanaeljones** [comment]
Since we already have a repo, I'll need to rename it right before the transfer, then accept the transfer, then delete the old copy.

**Comment by nathanaeljones** [comment]
Or, if you want to keep it under your user name, you could give me write access?

**Comment by slluis** [comment]
What about transferring the repo to the mono org? then I can add you as repo admin.

**Comment by nathanaeljones** [comment]
That might work. I have a paid AppVeyor account for the windows, not sure if it will access those, but we can try. I'd also be happy to add you as an admin on the imazen/sharpen repo.

**Comment by slluis** [comment]
Ok, transfer done

**Comment by nathanaeljones** [comment]
Strangely, I still don't have push permissions, even though I clearly have owner rights. This is weird.

**Comment by nathanaeljones** [comment]
There are [some license issues](https://github.com/mono/sharpen/issues/39) around Sharpen shims (C#). 

https://github.com/mono/ngit/tree/master/Sharpen

Most have your name and license, but not all. Can you add headers to the files you hold copyright for to clarify which license they're under?  Also, do you think we should copy these shims into mono/sharpen?

**Pull request closed without merging**
